import { baselineArtifactUrl } from "../data/report-artifact-sources";
import { ArtifactIframePage } from "./artifact/ArtifactIframePage";

export function BaselinePage() {
  return (
    <ArtifactIframePage
      heading="agent-eval baseline"
      description="How well the AI agent obeys the instruction surface, as a pass-rate trend pulled straight from the git history of baseline.json. Regenerated by the dotfiles CI pipeline and served from the public artifact bucket."
      artifactUrl={baselineArtifactUrl}
      iframeTitle="agent-eval baseline dashboard"
    />
  );
}
