import { coverageArtifactUrl } from "../data/report-artifact-sources";
import { ArtifactIframePage } from "./artifact/ArtifactIframePage";

export function CoveragePage() {
  return (
    <ArtifactIframePage
      heading="bash test coverage"
      description="kcov line coverage for the shell test suite, generated by tests/cover/bash-coverage.sh. Regenerated by the dotfiles CI pipeline and served from the public artifact bucket."
      artifactUrl={coverageArtifactUrl}
      iframeTitle="bash test coverage report"
    />
  );
}
