import { coverageArtifactUrl } from "../data/report-artifact-sources";
import { useIngestedTestCoverageSnapshot } from "../data/test-coverage-snapshot";
import { ArtifactIframePage } from "./artifact/ArtifactIframePage";
import { IngestedCoverageSummary } from "./test-coverage/IngestedCoverageSummary";

export function CoveragePage() {
  const snapshot = useIngestedTestCoverageSnapshot();
  return (
    <ArtifactIframePage
      heading="bash test coverage"
      description="kcov line coverage for the shell test suite, generated by __tests__/cover/bash-coverage.sh. The headline run is the snapshot the dotfiles pipeline ingested under its own versioned contract; the kcov report below is the full per line drilldown."
      artifactUrl={coverageArtifactUrl}
      iframeTitle="bash test coverage report"
      summary={
        snapshot ? <IngestedCoverageSummary snapshot={snapshot} /> : undefined
      }
    />
  );
}
