import { buildReportHubCards } from "../data/report-hub-cards";

export function ReportsHubPage() {
  const reportCards = buildReportHubCards();
  return (
    <div>
      <h1 className="mt-2 mb-1 text-2xl font-semibold">dotfiles reports</h1>
      <p className="mb-6 max-w-[74ch] text-muted-foreground">
        Living dashboards for the dotfiles repo, regenerated on every push to{" "}
        <code>main</code>. No screenshots, no stale issues. Each page is built
        from the repo's own git history and test runs.
      </p>
      <div className="my-6 grid gap-4 [grid-template-columns:repeat(auto-fit,minmax(11.875rem,1fr))]">
        {reportCards.map((card) => (
          <a
            key={card.id}
            className="block rounded-lg border border-border bg-surface px-5 py-4 text-inherit no-underline transition-colors hover:border-primary"
            href={card.href}
          >
            <div className="text-[1.05rem] font-semibold text-primary">
              {card.title}
            </div>
            <div className="mt-1.5 text-sm text-muted-foreground">
              {card.description}
            </div>
          </a>
        ))}
      </div>
      <footer className="mt-12 border-t border-border pt-4 text-xs text-muted-foreground">
        Generated by the dotfiles CI pipeline ·{" "}
        <a
          className="text-primary"
          href="https://github.com/Castrozan/.dotfiles"
        >
          Castrozan/.dotfiles
        </a>
      </footer>
    </div>
  );
}
