import { buildReportHubCards } from "../data/report-hub-cards";

export function ReportsHubPage() {
  const reportCards = buildReportHubCards();
  return (
    <div className="reports-page reports-hub">
      <h1>dotfiles reports</h1>
      <p className="lede">
        Living dashboards for the dotfiles repo, regenerated on every push to{" "}
        <code>main</code>. No screenshots, no stale issues. Each page is built
        from the repo's own git history and test runs.
      </p>
      <div className="cards">
        {reportCards.map((card) => (
          <a key={card.id} className="card" href={card.href}>
            <div className="card-title">{card.title}</div>
            <div className="card-subtitle">{card.description}</div>
          </a>
        ))}
      </div>
      <footer>
        Generated by the dotfiles CI pipeline ·{" "}
        <a href="https://github.com/Castrozan/.dotfiles">Castrozan/.dotfiles</a>
      </footer>
    </div>
  );
}
