OPCODE_CONTINUATION = 0x0
OPCODE_TEXT = 0x1
OPCODE_BINARY = 0x2
OPCODE_CONNECTION_CLOSE = 0x8
OPCODE_PING = 0x9
OPCODE_PONG = 0xA

FINAL_FRAGMENT_BIT = 0x80
MASK_BIT = 0x80
PAYLOAD_LENGTH_FIELD_MASK = 0x7F
OPCODE_FIELD_MASK = 0x0F

SEVEN_BIT_LENGTH_INDICATES_SIXTEEN_BIT = 126
SEVEN_BIT_LENGTH_INDICATES_SIXTY_FOUR_BIT = 127
SIXTEEN_BIT_LENGTH_CEILING = 65536

NORMAL_CLOSURE_STATUS_CODE = 1000
