import {
  REPORTS_MOUNT_PATH,
  USAGE_DASHBOARD_MOUNT_PATH,
} from "@platform/config";
import { INGESTION_TOPIC_CONTRACTS } from "@platform/ingestion-contracts";

export interface ReportHubCard {
  readonly id: string;
  readonly title: string;
  readonly description: string;
  readonly href: string;
}

export function buildReportHubCards(): ReportHubCard[] {
  return [
    {
      id: "baseline",
      title: "agent-eval baseline",
      description:
        "How well the AI agent obeys the instruction surface, as a pass-rate trend pulled straight from the git history of baseline.json.",
      href: `${REPORTS_MOUNT_PATH}baseline/`,
    },
    {
      id: "quality",
      title: "how quality is measured",
      description:
        "The testing pyramid behind the agent: static evals, integration, real end-to-end sessions, the gold-standard scorecard and the paired instruction-loading experiment.",
      href: `${REPORTS_MOUNT_PATH}quality/`,
    },
    {
      id: "coverage",
      title: "bash test coverage",
      description:
        "kcov line coverage for the shell test suite, generated by the repo's own coverage run.",
      href: `${REPORTS_MOUNT_PATH}coverage/`,
    },
    {
      id: "usage",
      title: "token usage across accounts",
      description:
        "Claude Code token consumption per account, anonymized to opaque labels and pulled from each machine's stats-cache. Cache-read tokens are the headline cost.",
      href: USAGE_DASHBOARD_MOUNT_PATH,
    },
    {
      id: "topics",
      title: "ingestion topics",
      description: `The ${INGESTION_TOPIC_CONTRACTS.length} contracted topics this site accepts, the version each is validated under, and when a producer last delivered one.`,
      href: `${REPORTS_MOUNT_PATH}topics/`,
    },
  ];
}
